# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test CI

on:
  push:
    branches: [ feature/test ]
  pull_request:
    branches: [ feature/test ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [16.2.0]
        version: [latest]
      fail-fast: false
      
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          
     - name: Install Dependencies
        run: npm install
        
     - name: Run test
       env: 
         CODE_VERSION: ${{ matrix.version }}
       run: npm run ci-test --if-present
